### ISSUE TITLE
When using F360 component references, ACDC4Robot does not export unique links

### ISSUE THREAD

**Issue by nmolinski** [bionicdl-sustech/ACDC4Robot#3]
## Problem

I have a design that uses reusable components (i.e. the leg part is reusable for both left and right sides).

In Fusion360, my robot has this hierachy:

robot
|-leg:1
|-body:1
|-leg:2

Fusion360 imports components with their basename, but to differentiate them, appends a `:<ID>` to the name.

When ACDC4Robot exports the URDF file, the `name` used for the links/joints do not include the unique identifier. i.e

```xml
    <link name="leg">
        <inertial>
   ...
    <link name="leg">
        <inertial>
```

instead of

```xml
    <link name="leg:1">
        <inertial>
   ...
    <link name="leg:2">
        <inertial>
```

This causes a failure in the UDRF import for tools such as PyBullet, RViz, etc.

## Solution

Add component IDs to the exported link/joint names

## Information

Platform: Fusion360 2.0.20754 arm64 [Native] MacOS
Python: 3.13
pybullet: 3.2.6

**Comment by asibatian** [comment]
Your are right. `:<ID>` is the id for occurrence in Fusion360 and I just remove all the suffix when exporting URDF.

But I suggest you make occurrence independent by right click it and manually rename the occurrence using identifier.

Or, just comment `s = re.sub(r':.*$', '', s)` at `ACDC4Robot/core/utils.py` will solve your problem.

**Comment by Nuofan-SUSTech** [comment]
Your are right. `:<ID>` is the id for occurrence in Fusion360 and I just remove all the suffix when exporting URDF.

But I suggest you make occurrence independent by right click it and manually rename the occurrence using identifier.

Or, just comment `s = re.sub(r':.*$', '', s)` at `ACDC4Robot/core/utils.py` will solve your problem.
